### ISSUE TITLE
Vector arrow not shown in astro starlight project

### ISSUE THREAD

**Issue by obiscr** [remarkjs/remark-math#102]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

rehype-katex(7.0.1) / remark-math(6.0.0)

### Link to runnable example

https://codesandbox.io/p/devbox/2k43df

### Steps to reproduce

Just open ths sandbox, and you will see it.

### Expected behavior

The vector arrow can be displayed normally, like this

<img width="270" alt="image" src="https://github.com/user-attachments/assets/fdd73703-917b-4e75-bdb4-baef1fad72e3">

### Actual behavior

The arrow not shown

<img width="328" alt="image" src="https://github.com/user-attachments/assets/9a6f9423-813d-42c9-9502-a80a11ff6de1">

### Affected runtime and version

v18.20.0

### Affected package manager and version

pnpm@9.3.0

### Affected OS and version

macOS 13.6.7

### Additional

I found the latex is showing in this tag

```html
<span class="accent-body" style="left:-0.1522em;">
</span>
```

I found this classes, which has the default style

```css
element.style {
    left: -0.1522em;
}

.katex .accent .accent-body:not(.accent-full) {
    width: 0;
}

.katex .accent .accent-body {
    position: relative;
}

.katex .vlist>span>span {
    display: inline-block;
}

.katex * {
    -ms-high-contrast-adjust: none !important;
    border-color: currentColor;
}
```

I found that once I used the following custom style to rewrote the default style, the arrows were displayed correctly

```css
.katex .accent .accent-body:not(.accent-full) {
    width: 9px !important;
}

.katex .accent .accent-body {
    left: 0 !important;
}
```
I hope this information is useful
